export interface SurveyPoint {
    State: string,
    County: string,
    Jurisdiction: string,
    Updated?: string,
    Total?: string,
    NonUtil?: string,
    Roads?: string,
    Water?: string,
    Sewer?: string,
    Drain?: string,
    Parks?: string,
    Library?: string,
    Fire?: string,
    Police?: string,
    GenGov?: string,
    Schools?: string,
    Other?: string,
    Othersd?: string,
  }